base_url = "https://log.preranasubedi.com.np"

# about me
author ="(i@preranasubedi.com.np) Prerana Subedi"
title = "sunakhari's logs"
description = "I just write things."

# disable sass and search index
compile_sass = false
build_search_index = false

# generate atom feed
feed_filenames = [ "atom.xml", "rss.xml" ]
generate_feeds = true

# enable tags
taxonomies = [
    {name = "tags", output = true}
]

[extra]
url="log.preranasubedi.com.np"
email = "i@preranasubedi.com.np"
profile = "/thumbnail.png"
note = "I just love to write, that's all."
